# Generated by Django 2.1.7 on 2019-08-10 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('catagory', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('actors', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('sub_language', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=6)),
                ('image', models.ImageField(upload_to='posters')),
                ('price', models.FloatField()),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Movie_catagory', to='polls.Catagory')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='movies',
            field=models.ManyToManyField(to='polls.Movie'),
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basket_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
