# Generated by Django 2.1.7 on 2019-08-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190810_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='movies',
            field=models.ManyToManyField(null=True, to='polls.Movie'),
        ),
    ]
