# Generated by Django 2.1.7 on 2019-08-14 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190814_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_details', to='polls.Basket')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_movie', to='polls.Movie')),
            ],
        ),
    ]
