# Generated by Django 2.1.7 on 2019-08-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_basketdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='movies',
        ),
    ]
