# Generated by Django 2.1.7 on 2019-08-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_basket_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketdetails',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
