# Generated by Django 2.1.7 on 2019-08-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190814_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
